# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: 'windows-latest'

jobs:
  - job:
    displayName: Web App
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '16.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
      displayName: 'npm install'

    - script: |
        npm run build
      displayName: 'npm run build'

    - task: PowerShell@2
      displayName: 'Show directories'
      inputs:
        targetType: 'inline'
        script: |
          ls
          ls build

    # https://docs.microsoft.com/en-us/azure/devops/pipelines/library/connect-to-azure?view=azure-devops
    - task: AzureFileCopy@4
      inputs:
        SourcePath: 'build\*'
        azureSubscription: '--Service Connection Name--'
        Destination: 'AzureBlob'
        storage: '--Azure storage name--'
        ContainerName: '$web'
        BlobPrefix: '--Sub directory of Azure storage--'
